### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by unixorn** [theogandara/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the name is awfully generic. Please consider renaming it to something descriptive, or even just name it after your github username.

I also prefer to add themes with screen shots in their `readme` so that users can see what they look like without having to install them.

Finally, please add a license file, some people won't use any code that doesn't have a license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by theogandara** [comment]
Hello,

Thank you for your feedback and suggestions. I have made the necessary changes to address the concerns mentioned.

I have also included screenshots of the plugin's themes in the readme file. This way, users can preview the different themes without the need to install them, providing a better user experience.

Furthermore, I have added a license file to the repository. I understand the importance of licensing and its impact on the usage of open-source code.

Once again, thank you for bringing these matters to my attention. I hope the changes I made meet your expectations. If you have any further suggestions or concerns, please let me know.

Best regards,
Théo Gandara
